apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: jwmgo9vd9-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jwmgo9vd9-python 
  name: jwmgo9vd9-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: jwmgo9vd9-python 
